"""Live LLM Agent connecting to Gemini, OpenAI, Anthropic, or Ollama.

Enables real-time cognitive reasoning and code generation for the Autonomous Self-Improvement Loop.
"""

from __future__ import annotations

import json
import logging
import os
import re
from typing import List, Optional, Tuple

from alhsi.agents.base import BaseAgent
from alhsi.core.types import Hypothesis, PresetConfig, Trial

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are an Autonomous Software Optimization Agent operating within a recursive self-improvement loop.
Your objective is to optimize the target source code to improve the specified metric.

Rules:
1. You may ONLY modify the provided target file.
2. Formulate a clear, grounded scientific hypothesis before making changes.
3. Keep code modifications focused and atomic.
4. Output your response in strict JSON format:
{
  "title": "<short descriptive title of hypothesis>",
  "category": "<architecture | optimizer | hyperparameter | systems | algorithmic>",
  "description": "<detailed rationale for why this change will improve the metric>",
  "expected_impact": "<expected metric change>",
  "code": "<COMPLETE replacement code for the target file>"
}
Do NOT return markdown fences around the JSON, return ONLY the raw JSON string.
"""


class LLMAgent(BaseAgent):
    """Real LLM Agent calling external or local LLM APIs."""

    def __init__(
        self,
        provider: str = "gemini",  # "gemini", "openai", "ollama", "anthropic"
        model: Optional[str] = None,
        api_key: Optional[str] = None,
    ):
        self.provider = provider.lower()
        self.model = model
        self.api_key = api_key or os.environ.get("GEMINI_API_KEY") or os.environ.get("OPENAI_API_KEY")

    def _build_prompt(
        self,
        current_code: str,
        history: List[Trial],
        config: PresetConfig,
        trial_num: int,
    ) -> str:
        history_summary = []
        for t in history[-5:]:  # Last 5 trials
            history_summary.append(
                f"- Trial #{t.trial_num}: '{t.hypothesis.title}' -> Status: {t.status.value}, "
                f"Metric: {t.trial_metric} (Baseline: {t.baseline_metric}), "
                f"Delta: {t.metric_delta or 'N/A'}"
            )
        history_str = "\n".join(history_summary) if history_summary else "No prior trials yet."

        direction = "LOWER is better" if config.lower_is_better else "HIGHER is better"

        return f"""Target File: {config.target_file}
Metric to optimize: {config.metric_name} ({direction})
Current Best Metric: {config.baseline_metric} {config.unit}

Prior Experiment History:
{history_str}

Current Target Code:
```python
{current_code}
```

Now, propose Trial #{trial_num}. Formulate your hypothesis and emit the complete new code in the requested JSON format."""

    def propose_change(
        self,
        current_code: str,
        history: List[Trial],
        config: PresetConfig,
        trial_num: int,
    ) -> Tuple[Hypothesis, str]:
        prompt = self._build_prompt(current_code, history, config, trial_num)

        try:
            if self.provider == "gemini":
                raw_json = self._call_gemini(prompt)
            elif self.provider == "openai":
                raw_json = self._call_openai(prompt)
            elif self.provider == "ollama":
                raw_json = self._call_ollama(prompt)
            else:
                raise ValueError(f"Unsupported provider: {self.provider}")

            parsed = json.loads(raw_json)
            hyp = Hypothesis(
                title=parsed.get("title", f"LLM Optimization #{trial_num}"),
                category=parsed.get("category", "llm_generated"),
                description=parsed.get("description", "Generated by LLM agent"),
                expected_impact=parsed.get("expected_impact", "Metric improvement"),
            )
            code = parsed.get("code", current_code)
            return hyp, code

        except Exception as e:
            logger.warning(f"LLM call failed ({e}), falling back to heuristic hypothesis.")
            return Hypothesis(
                title=f"Fallback Trial #{trial_num} (LLM Error: {type(e).__name__})",
                category="fallback",
                description=f"LLM call encountered error: {str(e)}",
                expected_impact="Neutral",
            ), current_code

    def _call_gemini(self, prompt: str) -> str:
        import google.generativeai as genai
        api_key = self.api_key or os.environ.get("GEMINI_API_KEY")
        if not api_key:
            raise ValueError("GEMINI_API_KEY is not set.")
        genai.configure(api_key=api_key)
        model_name = self.model or "gemini-1.5-flash"
        model = genai.GenerativeModel(
            model_name=model_name,
            system_instruction=SYSTEM_PROMPT,
            generation_config={"response_mime_type": "application/json"},
        )
        resp = model.generate_content(prompt)
        return resp.text.strip()

    def _call_openai(self, prompt: str) -> str:
        from openai import OpenAI
        api_key = self.api_key or os.environ.get("OPENAI_API_KEY")
        if not api_key:
            raise ValueError("OPENAI_API_KEY is not set.")
        client = OpenAI(api_key=api_key)
        model_name = self.model or "gpt-4o-mini"
        resp = client.chat.completions.create(
            model=model_name,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
            response_format={"type": "json_object"},
        )
        return resp.choices[0].message.content.strip()

    def _call_ollama(self, prompt: str) -> str:
        import requests
        model_name = self.model or "llama3.2"
        resp = requests.post(
            "http://localhost:11434/api/generate",
            json={
                "model": model_name,
                "system": SYSTEM_PROMPT,
                "prompt": prompt,
                "stream": False,
                "format": "json",
            },
            timeout=45.0,
        )
        resp.raise_for_status()
        return resp.json().get("response", "{}")
